apiVersion: apps/v1
kind: Deployment
metadata:
  name: jerryholland-filestore-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: filestore-server
  template:
    metadata:
      labels:
        app: filestore-server
    spec:
      containers:
      - name: filestore-server-container
        image: jwh3times/filestore-server:latest
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health          # The path to check for the liveness probe
            port: 5000             # The port to check on
          initialDelaySeconds: 15  # Wait this many seconds before starting the probe
          periodSeconds: 10        # Check the probe every 10 seconds
        readinessProbe:
          httpGet:
            path: /health          # The path to check for the readiness probe
            port: 5000             # The port to check on
          initialDelaySeconds: 5   # Wait this many seconds before starting the probe
          periodSeconds: 5         # Check the probe every 5 seconds